spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: auth
    password: auth_dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
app:
  jwt:
    secret: "dev-only-secret-nao-usar-em-producao-precisa-ter-32-bytes-no-minimo"
    access-token-ttl: PT15M
    refresh-token-ttl: P7D
  password-reset:
    token-ttl: PT15M
server:
  port: 8080
